### ISSUE TITLE
Error when installing IF 1.0 rc1 on Revo 2.0.0-pl rev#7177 

### ISSUE THREAD

**Issue by phron** [splittingred/If#1]
Hi Shaun

I'm facing this issue with IF snippet, error message during install but "succesfully installed" shown at the end, no IF snippet in the Elements tree, IF appears as "installed" in package manager...
you can see details on the forum http://modxcms.com/forums/index.php/topic,51679.msg300161/topicseen.html#msg300161

Thanks for your help...

**Comment by phron** [comment]
My first thought was for a misconfiguration (my side) but Shamblett tried too and his answer is "Just tried on one of my dev boxes, getting the fault you describe so it looks like the IF package is borked at the mo."...
Could you have a look at it please ? (I know you have not a lot of time regarding the planned date -22th july?- for the GA, but IF is so useful ... )
Thanks

**Comment by splittingred** [comment]
This is due to a bug in PL, actually, which doesnt allow less than 2-character Element names: http://svn.modxcms.com/jira/browse/MODX-2170
