### ISSUE TITLE
[request] Add operator "inarray"

### ISSUE THREAD

**Issue by KristianP** [splittingred/If#2]
Hi Shaun,

i think an "inarray" operator would be very useful for future releases of "If".

I extended my "If" snippet with following code:

case 'in_array':
case 'inarray':
case 'ia':
   !empty($operand) && $operand != '' ? $operand = explode(',',$operand):false;
   $output = !empty($subject) && $subject != '' && is_array($operand) && in_array($subject,$operand) ? $then : (isset($else) ? $else : '');
   break;

The snippet call:

[[If?
   &subject=`[[snippet]]`
   &operator=`inarray`
   &operand=`1,2,3`
   &then=`booom`
   &else=`pow`
]]

we use a comma delimiter to creat the array.

**Comment by splittingred** [comment]
done in 1.1-pl
